### ISSUE TITLE
cant't access to appdaemon

### ISSUE THREAD

**Issue by platini76** [JamesMcCarthy79/Home-Assistant-Config#59]
pi@raspberry:~ $ appdaemon -c /home/homeassistant/.homeassistant/appdaemon
Traceback (most recent call last):
  File "/usr/local/bin/appdaemon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 394, in main
    admain.main()
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/admain.py", line 213, in main
    config = yaml.load(config_file_contents)
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/pi/.local/lib/python3.5/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/local/lib/python3.5/dist-packages/appdaemon/utils.py", line 104, in _secret_yaml
    raise ValueError("{} not found in secrets file".format(node.value))
ValueError: 192.168.0.15 not found in secrets file

**Comment by platini76** [comment]
sorry I have solved.

**Comment by JamesMcCarthy79** [comment]
sorry just saw this I don't get notifications when someone raises an issue. Glad you managed to get it sorted.

**Comment by platini76** [comment]
hello James, thanks for reply.
I am a really noob in this field of home automation.
do you have sometimes to help me to solve some problems in my home?
I tried to copy your project but it is big, really big for me... need your help.. when and how and if you can
